export const APP_NAME = "Malimbe";

export const CONFIG = {
  APP_NAME,
  SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
  SECRET_KEY: process.env.NEXT_PUBLIC_SECRET_KEY,
  DOCUMENTATION_URL: process.env.NEXT_PUBLIC_DOCUMENTATION_URL,
  TERMS_OF_SERVICE_URL: process.env.NEXT_PUBLIC_TERMS_OF_SERVICE_URL,
  IDLE_TIMEOUT: process.env.NEXT_PUBLIC_IDLE_TIMEOUT,
};
